version: '3.8'
services:
 app:
  image: node:latest
  container_name: nodeapp
  environment:
   DB_HOST: mysql1
   DB_PORT: 3307
   DB_USER: root
   DB_PASSWORD: admin
  ports:
   - "3000:3000"
  command: ["bin/bash"]
  volumes:
   - ./:/code
  depends_on:
   - mysql1 
  stdin_open: true
  tty: true
 mysql1:
  image: mysql:5.7
  platform: linux/amd64
  restart: always
  container_name: db1
  environment:
   - MYSQL_ROOT_PASSWORD=admin
  ports:
   - '3307:3306'
  volumes:
   - .\db:/var/lib/mysql
  stdin_open: true
  tty: true
volumes: 
  db:
     driver: local
    
